name: CI
run-name: ${{ github.ref_name }} push run 🚀
on:
  push:
    branches:
      - obs-plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ✅
        uses: actions/checkout@v6

      - name: Download Python zip file 🐍
        run: |
          curl -L https://github.com/HichTala/draw2/releases/download/embedded-python/python-3.12.9-embed-amd64.zip -o python-3.12.9-embed-amd64.zip
          unzip python-3.12.9-embed-amd64.zip
          rm python-3.12.9-embed-amd64.zip
          rm python-3.12.9-embed-amd64/Lib/site-packages/draw/*

      - name: Copy Draw 2 files 📁
        run: |
          cp -r src/draw/* python-3.12.9-embed-amd64/Lib/site-packages/draw/
          zip -r python-3.12.9-embed-amd64.zip python-3.12.9-embed-amd64

      - name: Upload artifact 📤
        uses: actions/upload-artifact@v7
        with:
          name: python-3.12.9-embed-amd64.zip
          path: .

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts 🏺
        uses: actions/download-artifact@v8
        with:
          path: python-3.12.9-embed-amd64.zip

      - name: Create Release 🏷️
        uses: softprops/action-gh-release@v2
        with:
          tag_name: embedded-python
          files: ./python-3.12.9-embed-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}